server {
    listen 8080; # OpenShift runs as non-root, port 8080
    server_name _;
    root /opt/app-root/src;
    index index.html;

    location / {
        try_files $uri /index.html;
    }

    location /health {
        return 200 'ok';
        add_header Content-Type text/plain;
    }
}