apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: bank-backend
  namespace: bank-dev
  labels:
    app: bank-backend
spec:
  source:
    type: Git
    git:
      uri: https://github.com/Smohamed10/bank-accounts-portal.git
      ref: main
    contextDir: backend
  strategy:
    type: Source
    sourceStrategy:
      from:
        kind: ImageStreamTag
        name: python:3.11-ubi8
        namespace: openshift
  resources:
    requests:
      cpu: 300m
      memory: 512Mi
    limits:
      cpu: 1000m
      memory: 1Gi
  output:
    to:
      kind: ImageStreamTag
      name: bank-backend:latest
  triggers:
    - type: ConfigChange