apiVersion: v1
kind: Secret
metadata:
  name: bank-db-secret
  namespace: bank-dev
type: Opaque
data:
  DB_USER: cW5iYWRtaW4=
  DB_PASSWORD: UW5iQFNlY3VyZTIwMjUh
  POSTGRES_PASSWORD: UW5iQFNlY3VyZTIwMjUh